services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    networks: 
      - cloud
    depends_on:
      - nextclouddb
    ports:
      - 8081:80
    volumes:
      - ./html:/var/www/html
      - ./custom_apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nextclouddb

  nextclouddb:
      image: mariadb
      container_name: nextcloud-db
      restart: unless-stopped
      command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      networks: 
        - cloud
      volumes:
        - ./nextclouddb:/var/lib/mysql
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Istanbul
        - MYSQL_RANDOM_ROOT_PASSWORD=true
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud

networks:
  cloud:
    name: cloud
    driver: bridge