services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio_server
    hostname: minio
    command: server /data --console-address ":9001"

    ports:
      - "9005:9000"
      - "9006:9001"

    env_file:
      - .env

    volumes:
      - ./minio-data:/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9005/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  default:
    name: minio_network